SELECT TOP(1000)
    GUESTS.ID,
	GUESTS.FAX,
	GUESTS.NAME,
	GUESTS.ORDER_ID,
	ORDERS.ID,
	ORDERS.DESCRIPTION,
	ORDERS.PRICE
FROM
    ORDERS
INNER JOIN
    GUESTS ON ORDERS.ORDER_ID = GUESTS.ORDER_ID;
